name: higene
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^0.4.0+1
  cupertino_icons: ^0.1.3
  camera: ^0.5.8+2
  firebase_ml_vision: ^0.9.4
  flutter_camera_ml_vision: ^2.2.5
  video_player: ^0.10.11+1
  assets_audio_player: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/monster.json
  - assets/videos/video_0.mp4
  - assets/videos/video_1.mp4
  - assets/videos/video_2.mp4
  - assets/videos/video_3.mp4
  - assets/audios/scan_hand.wav
  - assets/audios/wash_hand.wav
  - assets/audios/safe_phone.wav
  - assets/audios/congrats.wav
  - assets/audios/oh_no.wav
  - assets/audios/hand_camera.wav
  - assets/audios/bgm.wav
  - assets/images/kuman.png
  - assets/images/scan_hand.png
  - assets/images/wash_hand.png